### ISSUE TITLE
Create Style Guide

### ISSUE THREAD

**Issue by garrett-vangilder** [TeamCharles/WorkFlow#1]
### Feature Description

Style guide will include naming conventions, comments, and general style rules.
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

https://github.com/TeamCharles/bangazon-inc/blob/master/projects/STYLEGUIDE.md
### Notes

Yet to be determined.

**Comment by matthamil** [comment]
Issue resolved
